import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import LayoutClient from "./layout.client";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
